# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import picture_pb2 as picture__pb2


class PictureConServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetImageVector = channel.unary_unary(
                '/picturetovector.PictureConService/GetImageVector',
                request_serializer=picture__pb2.ImageRequest.SerializeToString,
                response_deserializer=picture__pb2.VectorResponse.FromString,
                )


class PictureConServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetImageVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PictureConServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetImageVector': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImageVector,
                    request_deserializer=picture__pb2.ImageRequest.FromString,
                    response_serializer=picture__pb2.VectorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'picturetovector.PictureConService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PictureConService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetImageVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/picturetovector.PictureConService/GetImageVector',
            picture__pb2.ImageRequest.SerializeToString,
            picture__pb2.VectorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
